### ISSUE TITLE
Other ways to move pepper

### ISSUE THREAD

**Issue by d16310** [SoftBankRoboticsEurope/maplocalizeandmove#3]
Hello, Thank always thank you.

I have one question this time.
Since pepper is compatible with Android Studio, I feel that "SLAM", "Aruco", "localize", etc. are the main ways to move pepper.
However, I think that "line tracing" is also effective in some cases.

Is it difficult to achieve "line tracing" with the Android Studio version of pepper?
If you can,"OpenCV" "tensorflow" etc...
I would be grateful if you could tell me which one is effective.

Thank you for taking the time.

**Comment by renythomas** [comment]
Hello,

It is possible to use OpenCV or TensorFlow light on Pepper running the android version (Naoqi 2.9).
But we have never integrated a "line tracing" solution on it.
Best
